// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/cv-templates/ClassicSerif.tsx": () => import("../components/mockups/cv-templates/ClassicSerif.tsx"),
  "./components/mockups/cv-templates/Compact.tsx": () => import("../components/mockups/cv-templates/Compact.tsx"),
  "./components/mockups/cv-templates/Minimal.tsx": () => import("../components/mockups/cv-templates/Minimal.tsx"),
  "./components/mockups/cv-templates/ModernHeader.tsx": () => import("../components/mockups/cv-templates/ModernHeader.tsx"),
  "./components/mockups/cv-templates/PhotoRight.tsx": () => import("../components/mockups/cv-templates/PhotoRight.tsx"),
  "./components/mockups/cv-templates/SidebarDark.tsx": () => import("../components/mockups/cv-templates/SidebarDark.tsx"),
  "./components/mockups/cv-templates/SidebarTeal.tsx": () => import("../components/mockups/cv-templates/SidebarTeal.tsx"),
  "./components/mockups/cv-templates/TwoColumn.tsx": () => import("../components/mockups/cv-templates/TwoColumn.tsx")
};
